project:
  type: website

website:
  title: "Acoular"
  repo-url: https://github.com/acoular/blog2
  repo-actions: 
    - source
  repo-branch: main
  favicon: logo.png
  navbar:
    background: light
    logo: "logo.png"
    right:
      - text: Documentation
        href: https://www.acoular.org
      - icon: github
        href: https://github.com/acoular/acoular
format:
  html:
    theme: litera
    css: styles.css
    code-copy: true
